# Generated by Django 2.2.9 on 2020-01-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_user', models.TextField(default='name')),
                ('item_num', models.TextField(default='0000')),
                ('is_pass', models.BooleanField(default=False)),
            ],
        ),
    ]
