# Generated by Django 2.2.9 on 2020-01-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_applying'),
    ]

    operations = [
        migrations.CreateModel(
            name='STATE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_state', models.CharField(choices=[('A', 'Available'), ('C', 'Check'), ('P', 'Pass')], default='A', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
