# Generated by Django 2.2.9 on 2020-01-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200121_0333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STATE',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('C', 'Check'), ('P', 'Pass')], default='A', max_length=1),
        ),
    ]
