# Generated by Django 2.2.9 on 2020-01-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_is_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applying',
            name='is_pass',
        ),
    ]
