# Generated by Django 2.2.9 on 2020-01-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_applying_is_pass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applying',
            old_name='item_num',
            new_name='item_id',
        ),
        migrations.AddField(
            model_name='applying',
            name='item_name',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='applying',
            name='apply_user',
            field=models.TextField(default='user'),
        ),
    ]
