# Generated by Django 2.2.9 on 2020-01-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200121_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.TextField(default='0000')),
                ('item_name', models.TextField(default='none')),
                ('apply_user', models.TextField(default='user')),
                ('lent_time', models.DateTimeField(auto_now_add=True)),
                ('back_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='applying',
            name='is_lent',
            field=models.BooleanField(default=False),
        ),
    ]
