# Generated by Django 2.2.9 on 2020-01-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200122_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='item_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='back_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
